dist: xenial

language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-django18-djangorestframework363
    python: 2.7
  - env: TOX_ENV=py27-django19-djangorestframework363
    python: 2.7
  - env: TOX_ENV=py27-django110-djangorestframework363
    python: 2.7
  - env: TOX_ENV=py27-django111-djangorestframework363
    python: 2.7
  - env: TOX_ENV=py35-django20-djangorestframework377
    python: 3.5
  - env: TOX_ENV=py36-django111-djangorestframework363
    python: 3.6
  - env: TOX_ENV=py36-django20-djangorestframework377
    python: 3.6
  - env: TOX_ENV=py36-django21-djangorestframework382
    python: 3.6
  - env: TOX_ENV=py36-django22-djangorestframework392
    python: 3.6
  - env: TOX_ENV=py37-django20-djangorestframework377
    python: 3.7
  - env: TOX_ENV=py37-django21-djangorestframework382
    python: 3.7
  - env: TOX_ENV=py37-django22-djangorestframework392
    python: 3.7

install: pip install -r examples/requirements/test.txt

before_script:
  - sleep 1
  - mkdir -p examples/media/static
  - mkdir -p examples/logs/
  - mkdir -p examples/db/

script: travis_retry tox -e $TOX_ENV

after_success:
  - pip install coveralls
  - coveralls
